#!/usr/bin/env bash
# export GTK_IM_MODULE=xim
# export XMODIFIERS=@im=ibus
# export QT_IM_MODULE=xim

exec bwrap \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --ro-bind /usr/bin /usr/bin \
    --symlink usr/bin /bin \
    --ro-bind /usr/share/applications /usr/share/applications \
    --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
    --ro-bind /usr/share/glvnd /usr/share/glvnd \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/libdrm /usr/share/libdrm \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /etc/machine-id /etc/machine-id \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --dir /run/user/"$(id -u)" \
        --ro-bind "/run/user/$(id -u)/wayland-1" "/run/user/$(id -u)/wayland-1" \
        --ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0" \
        --ro-bind "/run/user/$(id -u)/pulse" "/run/user/$(id -u)/pulse" \
    --dev /dev \
    --dev-bind /dev/dri /dev/dri \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind $HOME/devBox/machine-id /etc/machine-id \
    --proc /proc \
    --tmpfs /tmp \
    --bind $HOME/devBox/.mozilla /home/n325/.mozilla \
    --bind $HOME/devBox/loading /home/n325/.load \
    --unshare-all \
    --share-net \
    --hostname n325 \
    --setenv HOME /home/n325 \
    --setenv GTK_THEME Adwaita:dark \
    --setenv MOZ_ENABLE_WAYLAND 1 \
    --setenv PATH /usr/bin \
    --die-with-parent \
    --new-session \
    --uid 512 --gid 113 \
    /usr/bin/firefox-developer-edition --no-remote --private-window -P
#/usr/bin/firefox-developer-edition --no-remote --private-window
