#!/usr/bin/env bash
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim

bwrap \
    --unshare-all \
    --share-net \
    --die-with-parent \
    --new-session \
    --symlink /usr/lib /lib \
    --symlink /usr/lib64 /lib64 \
    --ro-bind /usr/lib /usr/lib \
    --ro-bind /usr/lib64 /usr/lib64 \
    --dev /dev \
    --proc /proc \
    --tmpfs /tmp \
    --setenv HOME /home/example \
    --setenv GTK_THEME Adwaita:dark \
    --setenv PATH /usr/bin \
    --ro-bind /sys/dev/char /sys/dev/char \
    --ro-bind /sys/devices/pci0000:00 /sys/devices/pci0000:00 \
    --ro-bind /usr/share/applications /usr/share/applications \
    --ro-bind /usr/share/ca-certificates /usr/share/ca-certificates \
    --ro-bind /usr/share/fonts /usr/share/fonts \
    --ro-bind /usr/share/glib-2.0 /usr/share/glib-2.0 \
    --ro-bind /usr/share/glvnd /usr/share/glvnd \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /usr/share/libdrm /usr/share/libdrm \
    --ro-bind /usr/share/mime /usr/share/mime \
    --ro-bind /usr/share/X11/xkb /usr/share/X11/xkb \
    --ro-bind /usr/share/icons /usr/share/icons \
    --ro-bind /etc/fonts /etc/fonts \
    --ro-bind /etc/machine-id /etc/machine-id \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --dev-bind /dev/dri /dev/dri \
    --bind $HOME/.mozilla/firefox/devTest01 $HOME/.mozilla/firefox/devTest01 \
    --dir /run/user/"$(id -u)" \
        --ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0" \
        --ro-bind "/run/user/$(id -u)/pulse" "/run/user/$(id -u)/pulse" \
    # --bind $HOME/Desktop $HOME/Desktop \
    # --bind $HOME/Downloads $HOME/Downloads \
    # --ro-bind /opt/firefox /opt/firefox \
    # --symlink /opt/firefox/firefox /usr/bin/firefox \
    # --bind /home/example/.config/transmission /home/example/.config/transmission \
    # --bind /home/example/Downloads /home/example/Downloads \
    # --setenv HOME /home/example \
    --setenv GTK_THEME Adwaita:dark \
    --setenv MOZ_ENABLE_WAYLAND 1 \
    --setenv PATH /usr/bin \
/usr/bin/firefox
