#!/usr/bin/env bash

set -euo pipefail
(exec bwrap \
        --ro-bind /usr/bin /usr/bin \
        --ro-bind /usr/lib /usr/lib \
        --symlink usr/lib /lib64 \
        --tmpfs /usr/lib/gcc \
        --tmpfs $HOME \
        --ro-bind $HOME/.Xauthority $HOME/.Xauthority \
        --ro-bind $HOME/Desktop $HOME/Desktop \
        --tmpfs /tmp \
        --ro-bind /tmp/.X11-unix/X0 /tmp/.X11-unix/X0 \
        --unshare-all \
        --share-net \
        /usr/bin/sh) \
bash-4.4$ ls -AF \
.Xauthority  Desktop/
