#!/usr/bin/env bash
set -euo pipefail
(
    exec bwrap \
     --ro-bind /usr/bin/sh /usr/bin/sh \
     --ro-bind /usr/share /usr/share/ \
     --ro-bind /usr/lib /usr/lib \
     --ro-bind /usr/lib64 /usr/lib64 \
     --symlink /usr/lib64 /lib64 \
     --symlink /usr/lib /lib \
     --symlink /usr/bin /bin \
     --symlink /usr/bin /sbin \
     --proc /proc \
     --dev /dev \
     --dev-bind /dev/snd /dev/snd \
     --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
     --ro-bind /etc/resolv.conf /etc/resolv.conf \
     --ro-bind /etc/xdg /etc/xdg \
     --ro-bind /etc/gtk-2.0 /etc/gtk-2.0 \
     --ro-bind /etc/gtk-3.0 /etc/gtk-3.0 \
     --ro-bind /etc/fonts /etc/fonts \
     --ro-bind /etc/mime.types /etc/mime.types \
     --tmpfs /run \
     --ro-bind /run/user/"$(id -u)"/wayland-1 /run/user/"$(id -u)"/wayland-1 \
     --ro-bind "/run/user/$(id -u)/pipewire-0" "/run/user/$(id -u)/pipewire-0" \
     --ro-bind /run/user/"$(id -u)"/pulse /run/user/"$(id -u)"/pulse \
     --tmpfs /tmp \
     --ro-bind ~/.mozilla ~/.mozilla \
     # --ro-bind ~/.cache/mozilla ~/.cache/mozilla \
     --chdir ~/ \
     --unsetenv DBUS_SESSION_BUS_ADDRESS \
     --setenv MOZ_ENABLE_WAYLAND 1 \
     --unshare-all \
     --setenv HOME /home/ZE \
     --new-session \
     /usr/lib/firefox-developer-edition/firefox-bin
)
